version: "3.3"

services:

  vpf:
    build:
      context: ../
      dockerfile: docker/Dockerfile.gpu
    ipc: host
    runtime: nvidia
    image: nvidia/videoprocessingframework:vpf
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility

  vpf-tensorrt:
    build:
      context: ../
      dockerfile: docker/Dockerfile-tensorrt.gpu
    ipc: host
    runtime: nvidia
    image: nvidia/videoprocessingframework:vpf-tensorrt
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
