name: docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true


jobs:
  docker:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v3
    - name: Build docker containers
      run: | 
        make vpf-docker
        make vpf-docker-tensorrt 

    - name: Run tests
      run: | 
        make run_samples
    
    - name: Run samples
      run: | 
        make run_samples
    
