name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup FFmpeg
      env:
        CXX: /usr/lib/ccache/c++
        CC: /usr/lib/ccache/cc
      run: | 
        cd ~/FFmpeg/
        ./prepare.sh  
      
    - name: Setup pip
      run: |
        python3 -m venv /tmp/venv_vpf
        source /tmp/venv_vpf/bin/activate
        python3 -mpip install -r ./samples/requirements.txt    
        
    - name: Build and Install Package
      env:
        PKG_CONFIG_PATH: /home/gh-runner/FFmpeg/build_x64_release_shared/lib/pkgconfig
        CXX: /usr/lib/ccache/c++
        CC: /usr/lib/ccache/cc
        SKBUILD_CONFIGURE_OPTIONS: "-DCMAKE_CUDA_COMPILER_LAUNCHER=ccache"
      run: | 
        source /tmp/venv_vpf/bin/activate
        python3 -mpip install scikit-build
        python3 -mpip install . --verbose
        python3 -mpip install src/PytorchNvCodec --verbose

    - name: Run Tests
      run: |
        source /tmp/venv_vpf/bin/activate
        python3 -munittest discover tests

    - name: Run Samples
      run: |
        source /tmp/venv_vpf/bin/activate
        make run_samples_without_docker
